---
- name: Install Docker
  hosts: docker-server.pind
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - role: geerlingguy.docker
      docker_packages_state: present
    - role: portainer
...
