---
- hosts: olilab.pind

  tasks:
    - name: Install NFS client packages
      apt:
        name: nfs-common
        state: present

    - name: Create a directory for the NFS share
      file:
        path: /mnt/backupremoto
        state: directory

    - name: Add NFS mount to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: 'mediaserver.pind:/oliraid/backup/proxmox /mnt/backupremoto nfs defaults 0 0'
        state: present

    - name: Mount all filesystems mentioned in fstab
      command: mount -a
...