---
roles:
    - name: geerlingguy.repo-epel
    - name: geerlingguy.security
    - name: geerlingguy.docker
    - name: geerlingguy.ntp
    - name: chriswayg.msmtp-mailer
    - name: joenyland.samba
    - name: gantsign.visual-studio-code
