#
# Misc
#
hostname: '{{ inventory_hostname }}'
normal_user: '{{ theuser }}' 
samba_user_name: '{{ normal_user }}'
ssh_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDP5aQBaw3N2LG+URG8Xu+U4TouxklcXtdq7zt9lHX1S0d4wrGpQkDjhne1QBlGRRvpZQppqlhL1wdQeIeDJDqq/HlBo1yrJRhORd3UyNNbc4FD8gPPT1rVWfpYc0GQ2cC0L/erZLy/57dbwKV8V89U+kK/fvQr3VFMhFE4tWc5DG0nDP9efKqcFPrWTIgDGhsRWzMxDgGOQgWd912IVyrXlBw0cWhxSbL9qjsU9k3Wq2qtBNeholV63iuDsQZaHiEEvhJsOLhANraEI7uyqqjacR5/frYnTnmgXaxJo2qxv9Wt1ql+QYALeXeyshirxNm5Blz9j1TaUKQtQ1vYV0DCBtc39lcle0gzkKw0mRNNk7c3hr6cwUjl51OURPJ0UcnL+hCIXTMrjpxBXyH0uEZQE08eHqKql8WGJbms1SoPhMZpr5+kLkuPaKpyYShUJzDzZdY5bKW1YO8kKZhA3vwbVsuFcE+lvn+YweQ95SI5ChtoOuG5O//zaB4oNLPjGTU= olindo@olindo-pc-win11'



nfs_exports: [ "/oliraid *(rw,sync,no_root_squash)" ]

timezone: Europe/Rome

ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

keyboard_layout: us

username: '{{ theuser }}'

shell: /usr/bin/fish

#dotfiles_repo: https://github.com/notthebee/dotfiles

guid: "1000"

#
# Networking
# 
tailscale_enabled: no 

tailscale_exit_node: no

networks:
  - name: lan
    cidr: 192.168.2.0/24
    base: 192.168.2
    interface: ens18
    tailscale: yes # whether the subnet should be exposed to other Tailscale nodes
  - name: app
    cidr: 10.0.0.0/24
    base: 10.0.0
    tailscale: yes
  - name: iot
    cidr: 192.168.32.0/24
    base: 192.168.32
    tailscale: yes

#
# Docker apps
#
#
docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

services:
  - homeassistant
  - photoprism

#
# Packages
#
extra_packages:
  - fish
  - iperf3
  - speedtest-cli
  - htop
  - stow
  - exa
  - git
  - neofetch
  - neovim
  - tmux
  - mosh
  - rsync
  - lm-sensors
  - iotop
  - ncdu
  - pipx
  - curl
  - vlc
  - ffmpeg
  - handbrake
  - ethtool

extra_snap_packages:
  - filebot
  - telegram-desktop
  - whatsapp-for-linux
#
# Email credentials (for notifications)
#

email: o.pindaro@gmail.com

email_login: '{{ email }}'

email_smtp_host: smtp.gmail.com

email_smtp_port: 465

email_smtp_port_startls: 587

email_password: "{{ googlepass }}"

password: '{{ thepass }}'
samba_user_password: '{{ thepass }}'

# MSMTP
msmtp_accounts:
    - account: mailbox
      host: '{{ email_smtp_host }}'
      port: '{{ email_smtp_port_startls }}'
      auth: 'on'
      from: '{{ email }}'
      user: '{{ email }}'
      password: '{{ email_password }}'

msmtp_default_account: 'mailbox'

msmtp_alias_default: '{{ email }}'

#
# SSH (geerlingguy.security)
#
security_ssh_port: 69

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false
