#
# Misc
#
hostname: '{{ inventory_hostname }}'
normal_user: '{{ theuser }}' 
samba_user_name: '{{ normal_user }}'



nfs_exports: [ "/oliraid *(rw,sync,no_root_squash)" ]

timezone: Europe/Rome

ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

keyboard_layout: us

username: '{{ theuser }}'

shell: /usr/bin/fish

#dotfiles_repo: https://github.com/notthebee/dotfiles

guid: "1000"

#
# Networking
# 
tailscale_enabled: no 

tailscale_exit_node: no

networks:
  - name: lan
    cidr: 192.168.2.0/24
    base: 192.168.2
    interface: ens18
    tailscale: yes # whether the subnet should be exposed to other Tailscale nodes
  - name: app
    cidr: 10.0.0.0/24
    base: 10.0.0
    tailscale: yes
  - name: iot
    cidr: 192.168.32.0/24
    base: 192.168.32
    tailscale: yes

#
# Docker apps
#
#
docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

services:
  - homeassistant
  - photoprism

#
# Packages
#
extra_packages:
  - fish
  - iperf3
  - speedtest-cli
  - htop
  - stow
  - exa
  - git
  - neofetch
  - neovim
  - tmux
  - mosh
  - rsync
  - lm-sensors
  - iotop
  - ncdu
  - pipx
  - curl
  - vlc
  - ffmpeg
  - handbrake
  - ethtool
  - powertop
  - gdebi

extra_snap_packages:
  - telegram-desktop
  - whatsapp-for-linux
#
# Email credentials (for notifications)
#

email: o.pindaro@gmail.com

email_login: '{{ email }}'

email_smtp_host: smtp.gmail.com

email_smtp_port: 465

email_smtp_port_startls: 587

email_password: "{{ googlepass }}"

password: '{{ thepass }}'
samba_user_password: '{{ thepass }}'

# MSMTP
msmtp_accounts:
    - account: mailbox
      host: '{{ email_smtp_host }}'
      port: '{{ email_smtp_port_startls }}'
      auth: 'on'
      from: '{{ email }}'
      user: '{{ email }}'
      password: '{{ email_password }}'

msmtp_default_account: 'mailbox'

msmtp_alias_default: '{{ email }}'

#
# SSH (geerlingguy.security)
#
security_ssh_port: 69

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false

# default values for mediaserver Role
torrentDir: /oliraid/arrdata/qbittorrent
mediaDir: /oliraid/arrdata/media