---

- name: Make sure the jellyfin container is created and running
  register: jellyfin_result
  retries: 5
  until: jellyfin_result is succeeded
  community.general.docker_container:
    name: "jellyfin"
    image: "lscr.io/linuxserver/jellyfin:{{ jellyfin_version }}"
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Rome
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]
      start_period: 120s
      interval: 60s
      retries: "10"
      timeout: 60s
    networks: 
      - name: mediaserver-network
        ipv4_address: 10.8.2.18
    ports:
      - "8096:8096"
      - "8920:8920" #optional
      - "7359:7359/udp" #optional
      - "1900:1900/udp" #optional
    devices: 
      - /dev/dri/:/dev/dri/
    pull: yes
    state: "started"
    restart_policy: unless-stopped
    volumes: 
      - "{{ docker_dir }}/jellyfin/config:/config"
      - "{{ docker_dir }}/jellyfin/cache:/cache"
      - "{{ mediaDir }}:/media"
      - "{{ torrentDir }}:/torrents"
  tags: 
    - jellyfin
    - all

- name: Open jellyfin port
  ufw:
    state: enabled
    rule: allow
    port: "8096"
    to_ip: "192.168.50.0/24"
    from_ip: "192.168.50.0/24"
    proto: tcp
    comment: "Allow jellyfin access"
  tags: 
    - jellyfin
    - all