--- 
- name: Stampa le variabili
  debug:
    msg:
      - "ssh_user: {{ theuser }}"
      - "sudo_pass: {{ thepass }}"
- name: Update and upgrade packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Install extra snap packages
  community.general.snap:
    name: "{{ extra_snap_packages }}"
    classic: true
    state: present

- name: install ansible
  community.general.pipx:
    name: ansible
    install_deps: true
    state: present

- name: pipx inject ansible argcomplete
  community.general.pipx:
    name: ansible
    inject_packages: argcomplete
    state: present

- name: Settinge Gnome Graphic Properties /org/gnome/shell/extensions/dash-to-dock extend-height false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock"
    value: "['extend-height' , 'false']"

- name: Settinge Gnome Graphic Properties /org/gnome/shell/extensions/dash-to-dock dock-position BOTTOM
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock"
    value: "['dock-position' , 'BOTTOM']"
...