---

- name: Import Google's public key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome repository
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present

- name: Update apt and install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes

