---
- name: Pull the Portainer image
  community.general.docker_image:
      name: portainer/portainer-ce
      source: pull

- name: Run Portainer container
  community.general.docker_container:
    name:  portainer
    image: portainer/portainer-ce
    state: started
    published_ports: 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir }}/portainer_data:/data"
...
