---
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        state: latest

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists

    - name: lancia la shell e copia la chiave
      ansible.builtin.shell: curl -fsSL https://download.webmin.com/jcameron-key.asc | gpg --dearmor -o /usr/share/keyrings/webmin.gpg

    - name: aggiunge il repository
      ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/webmin.gpg] http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list

    - name: apt update di nuovo
      apt:
        update_cache: yes

    - name: installa webmin
      package:
        name: webmin
        state: present

    - name: systemctl start webmin
      ansible.builtin.service:
        name: webmin
        state: started
        enabled: yes

